### ISSUE TITLE
demultiplex failure

### ISSUE THREAD

**Issue by Salvobioinfo** [aryeelab/guideseq#49]
Running command line: `python guideseq.py all -m manifest_1.yaml`
after demultiplexing begins I receive: `IOError: [Errno 24] Too many open files: ... `

Upon inspection of the demultiplexed output directory, there is one file for every barcode. 
I saw other issue like mine, but others solutions don't work for me. 
My manifest file is:

```
reference_genome: /solid/Reference/GRCh38/GRCh38.d1.vd1.fa
output_folder: /tank/home/salvo/KATIA/OUTPUT

bwa: /solid/Programs/bwa-0.7.17/bwa
bedtools: /solid/Programs/bedtools2/bin/bedtools

demultiplex_min_reads: 1000

undemultiplexed:
    forward: /tank/USB/Undetermined_S0_L001_R1_001.fastq.gz
    reverse: /tank/USB/Undetermined_S0_L001_R2_001.fastq.gz
    index1: /tank/USB/Undetermined_S0_L001_I1_001.fastq.gz
    index2: /tank/USB/Undetermined_S0_L001_I2_001.fastq.gz

samples:
    control_a
        target:  
        barcode1: TTCTGCCT
        barcode2: CTCTCTAT
        description: Hek-MECP2_CTRLpos


    Hek-MECP2pos:
        target: GATTTTGACTTCACGGTAACTGG
        barcode1: TCGCCTTA
        barcode2: TAGATCGC
        description: Hek-MECP2pos


    control_b:
        target:  
        barcode1: GCTCAGGA
        barcode2: CTCTCTAT
        description: Hek-Hek-MECP2_CTRLneg


    Hek-MECP2neg:
        target: GATTTTGACTTCACGGTAACTGG
        barcode1: CTAGTACG
        barcode2: TAGATCGC
        description: Hek-MECP2neg
```
Any idea what is going on here? 
Salvatore

**Comment by Salvobioinfo** [comment]
I modified manifest file in:
```
reference_genome: /solid/Reference/GRCh38/GRCh38.d1.vd1.fa
output_folder: /tank/home/salvo/KATIA/OUTPUT

bwa: bwa
bedtools: bedtools

demultiplex_min_reads: 100000

undemultiplexed:
    forward: /tank/USB/Undetermined_S0_L001_R1_001.fastq.gz
    reverse: /tank/USB/Undetermined_S0_L001_R2_001.fastq.gz
    index1: /tank/USB/Undetermined_S0_L001_I1_001.fastq.gz
    index2: /tank/USB/Undetermined_S0_L001_I2_001.fastq.gz

samples:
    control:
        target:  
        barcode1: GCTCAGGA
        barcode2: CTCTCTAT
        description: Control


    HekMECP2neg:
        target: GATTTTGACTTCACGGTAACTGG
        barcode1: CTAGTACG
        barcode2: TAGATCGC
        description: Hek-MECP2ne
```
But I obtained always same results.
