### ISSUE TITLE
Filter step: Background file

### ISSUE THREAD

**Issue by jsacco1** [aryeelab/guideseq#63]
In my experiment, I have a control that does not have a background file. My understanding is that one is supposed to have a sample that was just transfected with the oligo tag without Cas9 as background control, but we do not have that sample. What do I put for the background file in this case?

Also can guideseq handle PAMs that are not NGG, as we have a different Cas9 that uses NNGRRT? If so, where can that be modified/accounted for?

**Comment by YichaoOU** [comment]
Hello, 

You can just use some fake barcode sequences and start the analysis. Let me know if it doesn't work. 

```
    control:
        target:
        barcode1: AAAAAAAA
        barcode2: AAAAAAAA
        description: Control
```

You can specify the PAM sequence by `PAM: NNGRRT` in the yaml file.

Yichao
